### PR TITLE
#56 Fix: Updated User model with timestamp and minor adjustments

### LINKED ISSUE #56: User created date is null in the database
Image

## AC
1. User created date is stored in the database automatically.

### PR DESCRIPTION
**Pull request by oleksandr-jr**

### CODE REVIEW

File: src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/model/User.java [hunk 1]
```diff
@@ -1,27 +1,37 @@
...
 @Builder(builderMethodName = "with")
-@Entity
 public class User {
+
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Column(name = "id")
     private Long userId;
+
     private String email;
```
Comment (aleos-dev) [inline src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/model/User.java:25]: Going forward, we can add some constraints and an index to the email field if it is deemed appropriate.

**Review by aleos-dev — APPROVED** [review]
Good job.
